#!/usr/bin/env python3
"""Generate parodius_gapwatch.lua: a Mesen2 script that logs and PAUSES on any
CPU read/write/exec touching ROM bytes in the graphics banks that are NOT part
of a known compressed stream ("the gaps") - to identify what those bytes are.

Also prints the gap inventory. Uses the gfxtrace corpus + the $C5BA static walk
(same enumeration as pce_gfx_export.py).
"""
import os
import re
import sys
import importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("rip", os.path.join(HERE, "pce_gfx_rip.py"))
rip = importlib.util.module_from_spec(spec)
spec.loader.exec_module(rip)
dec = rip.dec
exp_spec = importlib.util.spec_from_file_location("exp", os.path.join(HERE, "pce_gfx_export.py"))
exp = importlib.util.module_from_spec(exp_spec)
exp_spec.loader.exec_module(exp)


def main():
    rom_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "Parodius_Da__original.pce")
    traces = sys.argv[2:] or [os.path.join(HERE, "parodius_gfxtrace.txt")]
    rom = open(rom_path, "rb").read()
    blocks = exp.walk_table(rom, rip.parse_traces(traces))

    # stream extents
    extents = []
    for (bank, src) in sorted(blocks):
        hdr, dic, out, clen = dec.decode_block_full(rom, bank, src)
        off = dec.file_off(bank, src)
        extents.append((off, off + clen))
    extents.sort()

    # graphics banks = banks containing any stream byte
    gbanks = sorted(set(b for s, e in extents for b in range(s >> 13, (e - 1 >> 13) + 1)))

    # merge stream extents, then invert within each graphics bank
    merged = []
    for s, e in extents:
        if merged and s <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(merged[-1][1], e))
        else:
            merged.append((s, e))

    gaps = []
    for b in gbanks:
        lo, hi = b * 0x2000, (b + 1) * 0x2000
        cur = lo
        for s, e in merged:
            if e <= lo or s >= hi:
                continue
            if s > cur:
                gaps.append((cur, min(s, hi)))
            cur = max(cur, e)
        if cur < hi:
            gaps.append((cur, hi))
    gaps = [(s, e) for s, e in gaps if e - s >= 2]      # ignore 1-byte slivers

    # exclude thoroughly-known regions (would fire constantly, no mystery):
    # palette banks $38-$3B: colour blocks + pointer tables (the palette project)
    KNOWN = [(0x070000, 0x078000)]
    pruned = []
    for s, e in gaps:
        for ks, ke in KNOWN:
            if s < ke and e > ks:            # overlap: clip
                if s < ks:
                    pruned.append((s, ks))
                if e > ke:
                    pruned.append((ke, e))
                break
        else:
            pruned.append((s, e))
    gaps = sorted(p for p in pruned if p[1] - p[0] >= 2)

    total = sum(e - s for s, e in gaps)
    print("graphics banks: %d, streams: %d, gaps: %d, gap bytes: %d (%.1f KB)"
          % (len(gbanks), len(merged), len(gaps), total, total / 1024))
    big = sorted(gaps, key=lambda g: g[0] - g[1])[:10]
    for s, e in big:
        print("  gap $%06X-$%06X (%5d B, bank $%02X)" % (s, e - 1, e - s, s >> 13))

    with open(os.path.join(HERE, "parodius_census.lua"), "w", newline="\n") as f:
        f.write("""--AUTO-GENERATED by gen_gapwatch.py - do not edit.
--Combined census script:
-- 1) FALLTHROUGH monitor: logs each unique event reaching the original
--    engine paths on the SF2 build (DEC = decompressor $C25C: flips/
--    dynamics not diverted; VCOPY = $FE copy events $C168: not hooked).
-- 2) GAP watch: pauses + logs on any read/write/exec of ROM bytes in the
--    graphics banks that are NOT part of a known compressed stream.
--Log: parodius_census.txt

local log_file = io.open("D:/Projects/hacking/Parodius/parodius_census.txt", "a")
local function flog(s)
  if log_file then log_file:write(s .. "\\n"); log_file:flush() end
end
flog("=== run start ===")

-- ---------------- fallthrough monitor ----------------
local frames = 0
local ndec, nvc = 0, 0
local seen = {}

local function rd(a)  return emu.read(a, emu.memType.pceMemory, false) end
local function rd16(a) return emu.read16(a, emu.memType.pceMemory, false) end

local function on_dec()
  ndec = ndec + 1
  local ptr = rd16(0x2008)
  local key = string.format("D%02X%02X%04X", rd(ptr), rd(ptr + 1), rd16(ptr + 4))
  if not seen[key] then
    seen[key] = true
    flog(string.format(
      "DEC   F=%d stage=$%02X bank=$%02X p1=$%02X dst=$%04X.w src=$%04X",
      frames, rd(0x2093), rd(ptr), rd(ptr + 1), rd16(ptr + 2), rd16(ptr + 4)))
  end
end

local function on_vcopy()
  nvc = nvc + 1
  local ptr = rd16(0x2008)
  local key = string.format("V%04X%04X", rd16(ptr + 2), rd16(ptr + 4))
  if not seen[key] then
    seen[key] = true
    flog(string.format(
      "VCOPY F=%d stage=$%02X src=$%04X.w dst=$%04X.w words=%d",
      frames, rd(0x2093), rd16(ptr + 2), rd16(ptr + 4), rd(ptr + 6) * 16))
  end
end

emu.addMemoryCallback(on_dec, emu.callbackType.exec, 0xC25C, 0xC25C,
                      emu.cpuType.pce, emu.memType.pceMemory)
emu.addMemoryCallback(on_vcopy, emu.callbackType.exec, 0xC168, 0xC168,
                      emu.cpuType.pce, emu.memType.pceMemory)

-- ---------------- gap watch ----------------

-- sorted gap ranges [start, end) in ROM file offsets
local gaps = {
""")
        for s, e in gaps:
            f.write("  {0x%06X, 0x%06X},\n" % (s, e))
        f.write("""}

local function in_gap(off)
  local lo, hi = 1, #gaps
  while lo <= hi do
    local mid = math.floor((lo + hi) / 2)
    local g = gaps[mid]
    if off < g[1] then hi = mid - 1
    elseif off >= g[2] then lo = mid + 1
    else return true end
  end
  return false
end

local hits = 0
local paused_once = {}

local function on_access(kind)
  return function(addr, value)
    if not in_gap(addr) then return end
    hits = hits + 1
    local ok, st = pcall(emu.getState)
    local pc = (ok and st and st["cpu.pc"]) or 0
    local line = string.format("%s off=$%06X (bank $%02X) val=$%02X pc=$%04X",
        kind, addr, math.floor(addr / 8192), value or -1, pc)
    flog(line)
    emu.log(line)
    if not paused_once[addr - (addr % 64)] then
      paused_once[addr - (addr % 64)] = true
      emu.breakExecution()
    end
  end
end

-- watch each graphics bank region (ROM absolute offsets, pcePrgRom)
""")
        # one callback trio per contiguous run of graphics banks
        runs = []
        for b in gbanks:
            if runs and b == runs[-1][1]:
                runs[-1] = (runs[-1][0], b + 1)
            else:
                runs.append((b, b + 1))
        for b0, b1 in runs:
            s, e = b0 * 0x2000, b1 * 0x2000 - 1
            for kind, cb in (("READ", "read"), ("WRITE", "write"), ("EXEC", "exec")):
                f.write("emu.addMemoryCallback(on_access('%s'), emu.callbackType.%s, "
                        "0x%06X, 0x%06X, emu.cpuType.pce, emu.memType.pcePrgRom)\n"
                        % (kind, cb, s, e))
        f.write("""
emu.addEventCallback(function()
  frames = frames + 1
  emu.drawString(8, 8, string.format("census F=%d dec=%d vcopy=%d gap-hits=%d",
                 frames, ndec, nvc, hits), 0xFFFFFF, 0xA0000000)
end, emu.eventType.endFrame)
emu.displayMessage("Script", "census: fallthrough log + gap watch (pauses)")
""")
    print("wrote parodius_census.lua")


if __name__ == "__main__":
    main()
