--AUTO-GENERATED by gen_gapwatch.py - do not edit.
--Combined census script:
-- 1) FALLTHROUGH monitor: logs each unique event reaching the original
--    engine paths on the SF2 build (DEC = decompressor $C25C: flips/
--    dynamics not diverted; VCOPY = $FE copy events $C168: not hooked).
-- 2) GAP watch: pauses + logs on any read/write/exec of ROM bytes in the
--    graphics banks that are NOT part of a known compressed stream.
--Log: parodius_census.txt

local log_file = io.open("D:/Projects/hacking/Parodius/parodius_census.txt", "a")
local function flog(s)
  if log_file then log_file:write(s .. "\n"); log_file:flush() end
end
flog("=== run start ===")

-- ---------------- fallthrough monitor ----------------
local frames = 0
local ndec, nvc = 0, 0
local seen = {}

local function rd(a)  return emu.read(a, emu.memType.pceMemory, false) end
local function rd16(a) return emu.read16(a, emu.memType.pceMemory, false) end

local function on_dec()
  ndec = ndec + 1
  local ptr = rd16(0x2008)
  local key = string.format("D%02X%02X%04X", rd(ptr), rd(ptr + 1), rd16(ptr + 4))
  if not seen[key] then
    seen[key] = true
    flog(string.format(
      "DEC   F=%d stage=$%02X bank=$%02X p1=$%02X dst=$%04X.w src=$%04X",
      frames, rd(0x2093), rd(ptr), rd(ptr + 1), rd16(ptr + 2), rd16(ptr + 4)))
  end
end

local function on_vcopy()
  nvc = nvc + 1
  local ptr = rd16(0x2008)
  local key = string.format("V%04X%04X", rd16(ptr + 2), rd16(ptr + 4))
  if not seen[key] then
    seen[key] = true
    flog(string.format(
      "VCOPY F=%d stage=$%02X src=$%04X.w dst=$%04X.w words=%d",
      frames, rd(0x2093), rd16(ptr + 2), rd16(ptr + 4), rd(ptr + 6) * 16))
  end
end

emu.addMemoryCallback(on_dec, emu.callbackType.exec, 0xC25C, 0xC25C,
                      emu.cpuType.pce, emu.memType.pceMemory)
emu.addMemoryCallback(on_vcopy, emu.callbackType.exec, 0xC168, 0xC168,
                      emu.cpuType.pce, emu.memType.pceMemory)

-- ---------------- gap watch ----------------

-- sorted gap ranges [start, end) in ROM file offsets
local gaps = {
  {0x01A000, 0x01A8E2},
  {0x01BD05, 0x01C000},
  {0x02A000, 0x02B3E0},
  {0x02BFA1, 0x02C000},
  {0x02C000, 0x02D700},
  {0x02FEB2, 0x030000},
  {0x037F4D, 0x038000},
  {0x03FFA8, 0x040000},
  {0x040733, 0x042000},
  {0x067EEB, 0x068000},
  {0x06FFD1, 0x070000},
  {0x080463, 0x0804F8},
  {0x087FEB, 0x088000},
  {0x088BE9, 0x088E7B},
  {0x08BBF0, 0x08BD2E},
  {0x08BDD4, 0x08BF3C},
  {0x08BFE3, 0x08C000},
  {0x08C000, 0x08C20B},
  {0x08CA00, 0x08CE50},
  {0x08CEE9, 0x08D1F1},
  {0x08DE79, 0x08E000},
  {0x08E000, 0x08E2F8},
  {0x08E646, 0x08E93F},
  {0x08EC74, 0x08ED9B},
  {0x08EE22, 0x08EF3E},
  {0x08EFD0, 0x08F1CF},
  {0x08FFD6, 0x090000},
  {0x090000, 0x090095},
  {0x096893, 0x096A63},
  {0x096C80, 0x096E2E},
  {0x096F28, 0x097136},
  {0x09722C, 0x097394},
  {0x0976F5, 0x097781},
  {0x0978AD, 0x097B3E},
  {0x097D8D, 0x098000},
  {0x09FFCB, 0x0A0000},
  {0x0A7FF1, 0x0A8000},
  {0x0AFFED, 0x0B0000},
  {0x0B67B9, 0x0B692F},
  {0x0B6AF7, 0x0B6CC5},
  {0x0B6F24, 0x0B7158},
  {0x0B7426, 0x0B76BD},
  {0x0B79B7, 0x0B7CDB},
  {0x0B7FFA, 0x0B8000},
  {0x0BFF49, 0x0C0000},
  {0x0C7F80, 0x0C8000},
  {0x0C8D63, 0x0C9810},
  {0x0C9E02, 0x0CA000},
  {0x0CA000, 0x0CA639},
  {0x0CA8D5, 0x0CB226},
  {0x0CFF59, 0x0D0000},
  {0x0D7F6A, 0x0D8000},
  {0x0DFD79, 0x0E0000},
  {0x0E7E24, 0x0E8000},
  {0x0EFFC7, 0x0F0000},
  {0x0F7FD9, 0x0F8000},
  {0x0FFD2F, 0x100000},
}

local function in_gap(off)
  local lo, hi = 1, #gaps
  while lo <= hi do
    local mid = math.floor((lo + hi) / 2)
    local g = gaps[mid]
    if off < g[1] then hi = mid - 1
    elseif off >= g[2] then lo = mid + 1
    else return true end
  end
  return false
end

local hits = 0
local paused_once = {}

local function on_access(kind)
  return function(addr, value)
    if not in_gap(addr) then return end
    hits = hits + 1
    local ok, st = pcall(emu.getState)
    local pc = (ok and st and st["cpu.pc"]) or 0
    local line = string.format("%s off=$%06X (bank $%02X) val=$%02X pc=$%04X",
        kind, addr, math.floor(addr / 8192), value or -1, pc)
    flog(line)
    emu.log(line)
    if not paused_once[addr - (addr % 64)] then
      paused_once[addr - (addr % 64)] = true
      emu.breakExecution()
    end
  end
end

-- watch each graphics bank region (ROM absolute offsets, pcePrgRom)
emu.addMemoryCallback(on_access('READ'), emu.callbackType.read, 0x01A000, 0x01BFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('WRITE'), emu.callbackType.write, 0x01A000, 0x01BFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('EXEC'), emu.callbackType.exec, 0x01A000, 0x01BFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('READ'), emu.callbackType.read, 0x02A000, 0x041FFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('WRITE'), emu.callbackType.write, 0x02A000, 0x041FFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('EXEC'), emu.callbackType.exec, 0x02A000, 0x041FFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('READ'), emu.callbackType.read, 0x060000, 0x06FFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('WRITE'), emu.callbackType.write, 0x060000, 0x06FFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('EXEC'), emu.callbackType.exec, 0x060000, 0x06FFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('READ'), emu.callbackType.read, 0x076000, 0x077FFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('WRITE'), emu.callbackType.write, 0x076000, 0x077FFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('EXEC'), emu.callbackType.exec, 0x076000, 0x077FFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('READ'), emu.callbackType.read, 0x080000, 0x0FFFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('WRITE'), emu.callbackType.write, 0x080000, 0x0FFFFF, emu.cpuType.pce, emu.memType.pcePrgRom)
emu.addMemoryCallback(on_access('EXEC'), emu.callbackType.exec, 0x080000, 0x0FFFFF, emu.cpuType.pce, emu.memType.pcePrgRom)

emu.addEventCallback(function()
  frames = frames + 1
  emu.drawString(8, 8, string.format("census F=%d dec=%d vcopy=%d gap-hits=%d",
                 frames, ndec, nvc, hits), 0xFFFFFF, 0xA0000000)
end, emu.eventType.endFrame)
emu.displayMessage("Script", "census: fallthrough log + gap watch (pauses)")
