#!/usr/bin/env python3
"""Extract the game's compressed graphics as SF2-expansion build material.

Reads stream_manifest.txt (the definitive list of every compressed stream:
bank, src, flip variant, sizes, destination) and the user-supplied ROM, then
writes:
  gfx_bins/<bank>_<src>[_fN].bin   decompressed VRAM data per stream variant
  Parodius_SF2_assets.inc          expansion banks ($81+) with .incbin'd
                                   assets (first-fit, no bank crossing) +
                                   lookup tables in bank $80

The load hook matches a decompress event's [bank][src][p1] against the
tables; on a hit it streams the stored data instead of decompressing.

Usage:  pce_gfx_export.py <rom> [manifest]
"""
import os
import sys
import importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("dec", os.path.join(HERE, "pce_gfx_decode.py"))
dec = importlib.util.module_from_spec(spec)
spec.loader.exec_module(dec)

FIRST_BANK = 0x80          # LUT bank; assets from $81
BANK_SIZE = 0x2000


def read_manifest(path):
    entries = []
    for ln in open(path):
        ln = ln.strip()
        if not ln or ln.startswith(";"):
            continue
        f = ln.split()
        entries.append({"bank": int(f[0], 16), "src": int(f[1], 16),
                        "p1": int(f[2], 16), "dst": int(f[6], 16)})
    return entries


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return
    rom = open(sys.argv[1], "rb").read()
    manifest = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "stream_manifest.txt")
    entries = read_manifest(manifest)

    bindir = os.path.join(HERE, "gfx_bins")
    os.makedirs(bindir, exist_ok=True)

    assets = []
    for e in entries:
        hdr, dic, out, clen = dec.decode_block_full(rom, e["bank"], e["src"], e["p1"])
        name = "%02X_%04X" % (e["bank"], e["src"])
        if e["p1"]:
            name += "_f%d" % e["p1"]
        with open(os.path.join(bindir, name + ".bin"), "wb") as f:
            f.write(out)
        assets.append({"bank": e["bank"], "src": e["src"], "p1": e["p1"],
                       "name": name, "len": len(out), "dst": e["dst"]})

    # first-fit decreasing into expansion banks (no block crosses a bank)
    assets.sort(key=lambda a: -a["len"])
    banks = []
    for a in assets:
        for bi, b in enumerate(banks):
            if b[0] + a["len"] <= BANK_SIZE:
                a["ebank"] = FIRST_BANK + 1 + bi
                a["eoff"] = b[0]
                b[1].append(a)
                banks[bi] = (b[0] + a["len"], b[1])
                break
        else:
            a["ebank"] = FIRST_BANK + 1 + len(banks)
            a["eoff"] = 0
            banks.append((a["len"], [a]))
    assets.sort(key=lambda a: (a["ebank"], a["eoff"]))

    def page_of(ebank):
        return (ebank - 0x40) // 0x40      # $80-$BF -> 1, $C0-$FF -> 2, ...

    buckets = {}
    for a in assets:
        buckets.setdefault(a["bank"], []).append(a)
    assert len(buckets) <= 64, "too many event banks for the bucket directory"
    for bk, lst in buckets.items():
        assert len(lst) <= 255, "bucket $%02X exceeds 255 streams" % bk

    with open(os.path.join(HERE, "Parodius_SF2_assets.inc"), "w", newline="\n") as f:
        w = f.write
        w(";==================================================================\n")
        w("; AUTO-GENERATED by pce_gfx_export.py from stream_manifest.txt -\n")
        w("; do not edit by hand.\n")
        w(";\n")
        w("; Layout: bucket directory keyed by event bank -> per-bucket record\n")
        w("; list: [count] then count x 8-byte records\n")
        w(";   +0 src.lo  +1 src.hi  +2 (p1<<4)|sf2page  +3 asset WINDOW bank\n")
        w(";   +4 addr.lo +5 addr.hi +6 len.lo           +7 len.hi\n")
        w("; Flip variants (p1 1-3) are separate pre-flipped assets - match\n")
        w("; includes p1, so nothing decompresses at runtime for known content.\n")
        w(";==================================================================\n\n")
        w("; LUT bank is mapped at MPR3 ($6000) by the hook; assets at MPR4 ($8000).\n")
        w("  .bank $%02X, \"asset LUTs\"\n    .page 3\n    .org $6000\n\n" % FIRST_BANK)
        bks = sorted(buckets)
        w("sf2.bucket.count = %d\n\n" % len(bks))
        w("sf2.bucket.bank:\n")
        for bk in bks:
            w("    .db $%02X    ; %d streams\n" % (bk, len(buckets[bk])))
        w("\nsf2.bucket.ptr.lo:\n")
        for bk in bks:
            w("    .db low(sf2.bucket.%02X)\n" % bk)
        w("\nsf2.bucket.ptr.hi:\n")
        for bk in bks:
            w("    .db high(sf2.bucket.%02X)\n" % bk)
        for bk in bks:
            w("\nsf2.bucket.%02X:\n    .db %d\n" % (bk, len(buckets[bk])))
            for a in buckets[bk]:
                w("    .db $%02X,$%02X, $%02X,$%02X, low(asset.%s),high(asset.%s), $%02X,$%02X"
                  % (a["src"] & 0xFF, a["src"] >> 8,
                     (a["p1"] << 4) | page_of(a["ebank"]),
                     0x40 | (a["ebank"] & 0x3F), a["name"], a["name"],
                     a["len"] & 0xFF, a["len"] >> 8))
                w("   ; -> dst $%04X.w p1=%d\n" % (a["dst"], a["p1"]))
        w("\n")
        cur = None
        for a in assets:
            if a["ebank"] != cur:
                cur = a["ebank"]
                w("\n;------------------------------------------------------------------\n")
                w("  .bank $%02X, \"assets %02X\"\n    .page 4\n    .org $8000\n\n" % (cur, cur))
            w("asset.%s:                ; %d bytes -> dst $%04X.w\n"
              % (a["name"], a["len"], a["dst"]))
            w("  .incbin \"gfx_bins/%s.bin\"\n" % a["name"])

    used = sum(b[0] for b in banks)
    print("wrote %d bins (%d bytes) into banks $%02X-$%02X + LUT bank $%02X"
          % (len(assets), used, FIRST_BANK + 1, FIRST_BANK + len(banks), FIRST_BANK))


if __name__ == "__main__":
    main()
